### ISSUE TITLE
how to upload a file to google drive

### ISSUE THREAD

**Issue by zerorail** [llKYOTOll/GoogleDriveHandler#1]
hello,

i am trying to download and upload files to google drive which method should i use to upload a file to google drive and also which method should i use to find and download a file without user selecting it,

as i want to save user_db on google drive so making the user selecting it is a bad ux

**Comment by WorkWithAfridi** [comment]
Ahh, in that case you will have to implement google apis on your own. My
package opens the drive for the user to download files. It won't download
files automatically.

And for upload, that functionality has been removed in the recent version
due to google changing policies on their end. I will update package and the
update functionality in the near future.

**Comment by Noarge** [comment]
Hi WorkWithAfridi, 

Is there any alternative to upload files to google drive?
